# Generated by Django 5.2.2 on 2025-08-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usuarios',
        ),
    ]
