# Generated by Django 5.2.2 on 2025-08-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
