# Generated by Django 5.2.2 on 2025-10-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_name'),
        ('courses', '0013_coursetopics_topickeyword_keywordvariation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='courses.topickeyword')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_weights', to='chatbot.chatmessage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetopics')),
            ],
            options={
                'verbose_name': 'Peso de Tema',
                'verbose_name_plural': 'Pesos de Temas',
                'indexes': [models.Index(fields=['student', 'course', 'date'], name='chatbot_top_student_673df8_idx'), models.Index(fields=['course', 'topic', 'date'], name='chatbot_top_course__19faaa_idx'), models.Index(fields=['course', 'date'], name='chatbot_top_course__67d309_idx'), models.Index(fields=['keyword', 'date'], name='chatbot_top_keyword_ed11e3_idx')],
                'unique_together': {('message', 'keyword')},
            },
        ),
    ]
