# Generated by Django 5.2.2 on 2025-08-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='materias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='courses.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profesor', 'materia')},
            },
        ),
    ]
