# Generated by Django 5.2.2 on 2025-08-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Quitar la restricción compuesta
        migrations.AlterUniqueTogether(
            name='profesormateria',
            unique_together=None,
        ),

        # 2. Borrar los modelos antiguos ─ elimina sus tablas
        migrations.DeleteModel(name='ProfesorMateria'),
        migrations.DeleteModel(name='Materia'),

        # 3. Crear la nueva estructura
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=120)),
                ('description', models.TextField(blank=True, db_column='descripcion')),
                ('level', models.CharField(db_column='nivel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('owner', models.ForeignKey(
                    db_column='responsable',
                    limit_choices_to={'role': 'Teacher'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='created_courses',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'courses_materia'},
        ),

        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='fecha_union')),
                ('course', models.ForeignKey(
                    db_column='materia',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='enrollments',
                    to='courses.course')),
                ('student', models.ForeignKey(
                    db_column='estudiante',
                    limit_choices_to={'role': 'Student'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='enrollments',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_inscripcion',
                'unique_together': {('student', 'course')},
            },
        ),

        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='fecha_union')),
                ('course', models.ForeignKey(
                    db_column='materia',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='teachers',
                    to='courses.course')),
                ('teacher', models.ForeignKey(
                    db_column='profesor',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='courses',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_profesor_materia',
                'unique_together': {('teacher', 'course')},
            },
        ),
    ]

