# Generated by Django 5.2.2 on 2025-08-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, db_column='codigo', db_index=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, db_column='horario', max_length=60),
        ),
    ]
