# Generated by Django 5.2.2 on 2025-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tutoringschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourse',
            name='tutoring_details',
            field=models.TextField(blank=True, help_text='Añade aquí el horario, enlace de la reunión, ubicación, etc.', null=True, verbose_name='Detalles de la Monitoría'),
        ),
    ]
