# Generated by Django 5.2.2 on 2025-09-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_teachercourse_tutoring_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercourse',
            name='tutoring_details',
        ),
        migrations.CreateModel(
            name='TutoringSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3, verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de finalización')),
                ('location', models.CharField(help_text='Ej: Oficina 301, Laboratorio B, o enlace de Zoom/Meet', max_length=255, verbose_name='Ubicación o Enlace')),
                ('teacher_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_slots', to='courses.teachercourse')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('teacher_course', 'day', 'start_time')},
            },
        ),
    ]
