# Generated by Django 5.2.2 on 2025-09-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_knowledgebasefile'),
        ('courses', '0007_remove_teachercourse_tutoring_details_tutoringslot'),
    ]

    operations = [
    ]
