# Generated by Django 5.2.2 on 2025-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20250929_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefile',
            name='embeddings',
            field=models.JSONField(blank=True, default=list, help_text='Vector embeddings for chunks'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from PDF'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether the file has been processed for RAG'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='text_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Text chunks for RAG'),
        ),
    ]
