# Generated by Django 5.2.2 on 2025-09-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_knowledgebasefile_embeddings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='file',
            field=models.FileField(max_length=500, upload_to='knowledge_base/'),
        ),
    ]
