# Generated by Django 5.2.2 on 2025-10-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_group_options_group_ai_prompt_group_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del tema')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
            ],
            options={
                'verbose_name': 'Tema del Curso',
                'verbose_name_plural': 'Temas del Curso',
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Palabra clave principal')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='courses.coursetopics')),
            ],
            options={
                'verbose_name': 'Palabra Clave del Tema',
                'verbose_name_plural': 'Palabras Clave del Tema',
                'ordering': ['topic', 'keyword'],
                'unique_together': {('topic', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='KeywordVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=100, verbose_name='Variación')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='courses.topickeyword')),
            ],
            options={
                'verbose_name': 'Variación de Palabra Clave',
                'verbose_name_plural': 'Variaciones de Palabras Clave',
                'ordering': ['keyword', 'variation'],
                'unique_together': {('keyword', 'variation')},
            },
        ),
    ]
