name: Trigger Render Deploy

on:
  push:
    branches:
      - deploy-render

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
